plugins {
    id 'fabric-loom' version '1.17.19'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(
                rootProject.java_version as int
        )
    }
}

repositories {
    mavenCentral()

    maven {
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    implementation project(path: ':common', configuration: 'namedElements')
}