# ------------------------------------------------------------------
# Gradle
# ------------------------------------------------------------------

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# ------------------------------------------------------------------
# Mod
# ------------------------------------------------------------------

mod_id=scp_genesis
mod_name=SCP: Genesis
mod_version=0.1.3.5

# ------------------------------------------------------------------
# Minecraft
# ------------------------------------------------------------------

minecraft_version=1.21.1
neoforge_version=21.1.232

# ------------------------------------------------------------------
# Java
# ------------------------------------------------------------------

java_version=21