# ------------------------------------------------------------------
# Gradle
# ------------------------------------------------------------------

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# ------------------------------------------------------------------
# Mod
# ------------------------------------------------------------------

mod_id=scp_genesis
mod_name=SCP: Genesis
mod_version=0.1.4
version_type=alpha
version_id=18

# ------------------------------------------------------------------
# Minecraft
# ------------------------------------------------------------------

minecraft_version=1.21.1

# ------------------------------------------------------------------
# NeoForge
# ------------------------------------------------------------------

neoforge_version=21.1.250

# ------------------------------------------------------------------
# Fabric
# ------------------------------------------------------------------

fabric_loader_version=0.19.3
fabric_api_version=0.116.15+1.21.1

# ------------------------------------------------------------------
# Java
# ------------------------------------------------------------------

java_version=21