# ------------------------------------------------------------------
# Gradle
# ------------------------------------------------------------------

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# ------------------------------------------------------------------
# Mod
# ------------------------------------------------------------------

mod_id=scp_genesis
mod_name=SCP: Genesis
mod_version=0.2
version_type=beta
version_id=2

# ------------------------------------------------------------------
# Minecraft
# ------------------------------------------------------------------

minecraft_version=1.21.1

# ------------------------------------------------------------------
# NeoForge
# ------------------------------------------------------------------

neoforge_version=21.1.251

# ------------------------------------------------------------------
# Fabric
# ------------------------------------------------------------------

fabric_loader_version=0.19.5
fabric_api_version=0.116.17+1.21.1

# ------------------------------------------------------------------
# Java
# ------------------------------------------------------------------

java_version=21