modLoader="javafml"
loaderVersion="[4,)"
license="Custom"

[[mods]]
modId="scp_genesis"
version="0.1.4-alpha18"
displayName="SCP Genesis"
displayURL="https://saphira-studio.com"
logoFile="logo.png"
credits="Developed by Studio Saphira for the SCP: Genesis project"
authors="HeroFR, Studio Saphira"
description="SCP Genesis expands Minecraft with a complete SCP-inspired experience, advanced security systems, SCP entities, Copycat Blocks and many immersive gameplay mechanics."

[[dependencies.scp_genesis]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.232,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.scp_genesis]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"