package net.scp_genesis.common.copycatblocks.geometry.slope;

import net.minecraft.core.Direction;
import net.minecraft.world.level.block.state.properties.Half;
import net.scp_genesis.common.copycatblocks.geometry.*;
import org.jetbrains.annotations.NotNull;

/**
 * Defines the geometry of a Copycat Slope.
 *
 * <p>The canonical orientation is:
 *
 * <ul>
 *     <li>FACING = NORTH</li>
 *     <li>HALF = BOTTOM</li>
 *     <li>NORTH = low side of the slope</li>
 *     <li>SOUTH = high side of the slope</li>
 * </ul>
 *
 * <p>The canonical geometry is a right triangular prism composed of:
 *
 * <ul>
 *     <li>one bottom square</li>
 *     <li>one inclined upper face</li>
 *     <li>one south vertical square</li>
 *     <li>one west right triangle</li>
 *     <li>one east right triangle</li>
 * </ul>
 */
public final class CopycatGeometrySlope {

    private CopycatGeometrySlope() {
    }

    /*
     * ================================================================
     * DEFAULT GEOMETRY
     * ================================================================
     */

    /**
     * Returns the canonical NORTH/BOTTOM geometry.
     *
     * <p>The geometry is generated from the diagonal plane:</p>
     *
     * <pre>
     *     Y = 1 - Z
     * </pre>
     *
     * <p>The diagonal is therefore:</p>
     *
     * <pre>
     *     NORTH (Z = 0) -> Y = 1
     *     SOUTH (Z = 1) -> Y = 0
     * </pre>
     *
     * <p>This produces a right triangular prism obtained by cutting
     * a complete cube along a diagonal plane.</p>
     */
    public static CopycatFace[] getDefaultFaces() {

        /*
         * ============================================================
         * BOTTOM VERTICES
         * ============================================================
         */

        CopycatVertex bottomNorthWest =
                new CopycatVertex(
                        0.0F,
                        0.0F,
                        0.0F
                );

        CopycatVertex bottomNorthEast =
                new CopycatVertex(
                        1.0F,
                        0.0F,
                        0.0F
                );

        CopycatVertex bottomSouthWest =
                new CopycatVertex(
                        0.0F,
                        0.0F,
                        1.0F
                );

        CopycatVertex bottomSouthEast =
                new CopycatVertex(
                        1.0F,
                        0.0F,
                        1.0F
                );

        /*
         * ============================================================
         * DIAGONAL VERTICES
         * ============================================================
         *
         * These vertices are generated by CopycatSlopeMath.
         *
         * The canonical diagonal is:
         *
         *     Y = 1 - Z
         */

        CopycatVertex topNorthWest =
                CopycatSlopeMath.cutVerticalEdge(
                        0.0F,
                        0.0F
                );

        CopycatVertex topNorthEast =
                CopycatSlopeMath.cutVerticalEdge(
                        1.0F,
                        0.0F
                );

        CopycatVertex diagonalSouthWest =
                CopycatSlopeMath.cutVerticalEdge(
                        0.0F,
                        1.0F
                );

        CopycatVertex diagonalSouthEast =
                CopycatSlopeMath.cutVerticalEdge(
                        1.0F,
                        1.0F
                );

        return new CopycatFace[] {

                /*
                 * ----------------------------------------------------
                 * DOWN
                 * ----------------------------------------------------
                 */

                new CopycatFace(
                        Direction.DOWN,
                        new CopycatVertex[] {
                                bottomNorthWest,
                                bottomNorthEast,
                                bottomSouthEast,
                                bottomSouthWest
                        }
                ),

                /*
                 * ----------------------------------------------------
                 * NORTH
                 * ----------------------------------------------------
                 */

                new CopycatFace(
                        Direction.NORTH,
                        new CopycatVertex[] {
                                bottomNorthWest,
                                topNorthWest,
                                topNorthEast,
                                bottomNorthEast
                        }
                ),

                /*
                 * ----------------------------------------------------
                 * UP / SLOPE
                 * ----------------------------------------------------
                 */

                new CopycatFace(
                        Direction.UP,
                        new CopycatVertex[] {
                                topNorthWest,
                                diagonalSouthWest,
                                diagonalSouthEast,
                                topNorthEast
                        }
                ),

                /*
                 * ----------------------------------------------------
                 * WEST TRIANGLE
                 * ----------------------------------------------------
                 */

                new CopycatFace(
                        Direction.WEST,
                        new CopycatVertex[] {
                                bottomNorthWest,
                                bottomSouthWest,
                                topNorthWest
                        }
                ),

                /*
                 * ----------------------------------------------------
                 * EAST TRIANGLE
                 * ----------------------------------------------------
                 */

                new CopycatFace(
                        Direction.EAST,
                        new CopycatVertex[] {
                                bottomNorthEast,
                                topNorthEast,
                                bottomSouthEast
                        }
                )
        };
    }

    /*
     * ================================================================
     * ORIENTATION
     * ================================================================
     */

    /**
     * Returns the geometry for the requested orientation.
     *
     * @param facing horizontal orientation of the slope
     * @param half vertical orientation of the slope
     * @return the transformed slope faces
     */
    public static CopycatFace[] getFaces(
            @NotNull Direction facing,
            @NotNull Half half
    ) {
        CopycatFace[] source =
                getDefaultFaces();

        CopycatFace[] result =
                new CopycatFace[source.length];

        int rotations =
                getRotationCount(facing);

        for (int i = 0; i < source.length; i++) {

            CopycatFace sourceFace =
                    source[i];

            CopycatVertex[] vertices =
                    new CopycatVertex[
                            sourceFace.vertices().length
                            ];

            for (int j = 0; j < vertices.length; j++) {

                vertices[j] =
                        transformVertex(
                                sourceFace.vertices()[j],
                                rotations,
                                half
                        );
            }

            /*
             * The vertical reflection used for HALF.TOP reverses
             * the winding of every face.
             */
            if (half == Half.TOP) {
                reverseWinding(vertices);
            }

            Direction direction =
                    transformDirection(
                            sourceFace.direction(),
                            rotations,
                            half
                    );

            result[i] =
                    new CopycatFace(
                            direction,
                            vertices
                    );
        }

        return result;
    }

    private static @NotNull CopycatUV[] transformUV(
            @NotNull CopycatUV[] uv,
            @NotNull Direction direction,
            @NotNull Direction facing,
            @NotNull Half half
    ) {
        CopycatUV[] result =
                new CopycatUV[uv.length];

        int rotations =
                getRotationCount(facing);

        for (int i = 0; i < uv.length; i++) {

            CopycatUV transformed =
                    uv[i];

            /*
             * The rotation of the geometry must be reflected
             * on the UVs when the face changes orientation.
             */
            if (direction.getAxis().isHorizontal()) {
                transformed =
                        CopycatUVMapping.rotate(
                                transformed,
                                rotations
                        );
            }

            /*
             * HALF.TOP inverts geometry vertically.
             */
            if (half == Half.TOP) {
                transformed =
                        CopycatUVMapping.flipV(
                                transformed
                        );
            }

            result[i] =
                    CopycatUVMapping.clamp(
                            transformed
                    );
        }

        return result;
    }

    /**
     * Returns the UV coordinates for the requested Slope orientation.
     *
     * <p>The UV coordinates are calculated from the same transformed
     * faces returned by {@link #getFaces(Direction, Half)}.</p>
     *
     * <p>The returned array follows exactly the same face order as
     * {@link #getFaces(Direction, Half)}. Each inner array contains one
     * {@link CopycatUV} for every vertex of the corresponding face.</p>
     *
     * @param facing horizontal orientation of the slope
     * @param half vertical orientation of the slope
     * @return normalized UV coordinates for every vertex of every face
     */
    public static @NotNull CopycatUV[][] getUV(
            @NotNull Direction facing,
            @NotNull Half half
    ) {
        CopycatFace[] faces =
                getFaces(
                        facing,
                        half
                );

        CopycatUV[][] result =
                new CopycatUV[faces.length][];

        for (int i = 0; i < faces.length; i++) {

            CopycatFace face =
                    faces[i];

            CopycatUV[] faceUV =
                    CopycatSlopeUV.calculate(
                            face
                    );

            result[i] =
                    transformUV(
                            faceUV,
                            face.direction(),
                            facing,
                            half
                    );
        }

        return result;
    }

    /**
     * Returns the number of clockwise 90° rotations required to
     * transform the canonical NORTH orientation into the requested
     * horizontal facing.
     */
    private static int getRotationCount(
            @NotNull Direction facing
    ) {
        return switch (facing) {
            case NORTH -> 0;
            case EAST -> 1;
            case SOUTH -> 2;
            case WEST -> 3;

            case UP, DOWN ->
                    throw new IllegalArgumentException(
                            "Copycat Slope facing must be horizontal: "
                                    + facing
                    );
        };
    }

    /**
     * Transforms a canonical vertex according to FACING and HALF.
     *
     * <p>The transformation is delegated to the common geometry
     * mathematics utilities:</p>
     *
     * <ol>
     *     <li>the vertex is mirrored vertically for {@link Half#TOP};</li>
     *     <li>the vertex is rotated around the Y axis according to
     *     {@code FACING}.</li>
     * </ol>
     *
     * @param vertex the canonical vertex
     * @param rotations the number of clockwise 90° rotations
     * @param half the vertical half of the slope
     * @return the transformed vertex
     */
    private static @NotNull CopycatVertex transformVertex(
            @NotNull CopycatVertex vertex,
            int rotations,
            @NotNull Half half
    ) {
        CopycatVertex transformed =
                vertex;

        /*
         * HALF.TOP:
         *
         * Mirror the geometry vertically around Y = 0.5.
         */
        if (half == Half.TOP) {
            transformed =
                    CopycatGeometryMath.mirrorY(
                            transformed
                    );
        }

        /*
         * FACING:
         *
         * Rotate the geometry around the center of the block.
         */
        if (rotations != 0) {
            transformed =
                    CopycatGeometryMath.rotateY(
                            transformed,
                            rotations
                    );
        }

        return transformed;
    }

    /**
     * Transforms a face direction according to FACING and HALF.
     */
    private static Direction transformDirection(
            @NotNull Direction direction,
            int rotations,
            @NotNull Half half
    ) {
        Direction result =
                direction;

        /*
         * Rotate horizontal directions.
         */
        for (int i = 0; i < rotations; i++) {

            if (result.getAxis().isHorizontal()) {
                result =
                        result.getClockWise();
            }
        }

        /*
         * A vertical reflection swaps UP and DOWN.
         *
         * Horizontal directions remain unchanged by the reflection.
         */
        if (half == Half.TOP) {

            if (result == Direction.UP) {
                result = Direction.DOWN;

            } else if (result == Direction.DOWN) {
                result = Direction.UP;
            }
        }

        return result;
    }

    /**
     * Reverses the winding of a face.
     *
     * <p>Mirroring a geometry along the Y axis reverses its orientation.
     * Reversing the vertex order restores the expected winding.</p>
     */
    private static void reverseWinding(
            @NotNull CopycatVertex[] vertices
    ) {
        for (
                int first = 0,
                last = vertices.length - 1;
                first < last;
                first++,
                        last--
        ) {
            CopycatVertex temporary =
                    vertices[first];

            vertices[first] =
                    vertices[last];

            vertices[last] =
                    temporary;
        }
    }
}