plugins {
    id 'java-library'
    id 'fabric-loom' version '1.17.19'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(
                rootProject.java_version as int
        )
    }
}

repositories {
    mavenCentral()

    maven {
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

    mappings loom.officialMojangMappings()
}