package net.scp_genesis.copycatblocks.renderer.model;

import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.block.model.BakedQuad;
import net.minecraft.client.renderer.block.model.ItemOverrides;
import net.minecraft.client.renderer.block.model.ItemTransforms;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.core.Direction;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.SlabType;
import net.neoforged.neoforge.client.ChunkRenderTypeSet;
import net.neoforged.neoforge.client.model.data.ModelData;
import net.scp_genesis.copycatblocks.data.CopycatPart;
import net.scp_genesis.copycatblocks.provider.CopycatModelProvider;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;

public final class CopycatBakedModel implements BakedModel {

    /*
     * ================================================================
     * MODELS
     * ================================================================
     */

    /**
     * Base geometry used by a simple Copycat Block such as the Cube.
     */
    private final BakedModel baseModel;

    /**
     * Bottom slab geometry.
     */
    private final BakedModel bottomModel;

    /**
     * Top slab geometry.
     */
    private final BakedModel topModel;

    /**
     * Double slab geometry.
     */
    private final BakedModel doubleModel;


    /*
     * ================================================================
     * CONSTRUCTORS
     * ================================================================
     */

    /**
     * Constructor used by simple Copycat Blocks.
     */
    public CopycatBakedModel(
            @NotNull BakedModel baseModel
    ) {
        this.baseModel = baseModel;

        this.bottomModel = null;
        this.topModel = null;
        this.doubleModel = null;
    }

    /**
     * Constructor used by Copycat Slabs.
     */
    public CopycatBakedModel(
            @NotNull BakedModel bottomModel,
            @NotNull BakedModel topModel,
            @NotNull BakedModel doubleModel
    ) {
        this.baseModel = null;

        this.bottomModel = bottomModel;
        this.topModel = topModel;
        this.doubleModel = doubleModel;
    }


    /*
     * ================================================================
     * MODEL ACCESS
     * ================================================================
     */

    private BakedModel getBaseModel() {
        return java.util.Objects.requireNonNull(baseModel);
    }

    private BakedModel getBottomModel() {
        return java.util.Objects.requireNonNull(bottomModel);
    }

    private BakedModel getTopModel() {
        return java.util.Objects.requireNonNull(topModel);
    }

    private BakedModel getDoubleModel() {
        return java.util.Objects.requireNonNull(doubleModel);
    }


    /*
     * ================================================================
     * COPYCAT DATA
     * ================================================================
     */

    /**
     * Returns the copied BlockState associated with a Copycat part.
     */
    private static @Nullable BlockState getCopiedState(
            @NotNull ModelData modelData,
            @NotNull CopycatPart part
    ) {
        EnumMap<CopycatPart, BlockState> copiedStates =
                modelData.get(
                        CopycatModelProperties.COPIED_STATES
                );

        if (copiedStates == null) {
            return null;
        }

        return copiedStates.get(part);
    }


    /*
     * ================================================================
     * COPIED MODEL
     * ================================================================
     */

    /**
     * Returns the vanilla BakedModel corresponding to a copied state.
     */
    private static @Nullable BakedModel getCopiedModel(
            @Nullable BlockState copiedState
    ) {
        if (copiedState == null || copiedState.isAir()) {
            return null;
        }

        return CopycatModelProvider.getModel(copiedState);
    }


    /**
     * Returns the quads generated by a copied BlockState.
     */
    private static List<BakedQuad> getCopiedQuads(
            @NotNull BakedModel copiedModel,
            @NotNull BlockState copiedState,
            @Nullable Direction side,
            @NotNull RandomSource random,
            @Nullable RenderType renderType
    ) {
        return copiedModel.getQuads(
                copiedState,
                side,
                random,
                ModelData.EMPTY,
                renderType
        );
    }


    /*
     * ================================================================
     * TEXTURE SELECTION
     * ================================================================
     */

    /**
     * Finds the most appropriate quad from the copied model for the
     * specified Copycat quad.
     *
     * <p>We first try to find a quad with the same tint index.
     * This is important for blocks such as Grass Block, which use
     * tinted and non-tinted quads.</p>
     */
    private static @Nullable BakedQuad findMatchingCopiedQuad(
            @NotNull BakedModel copiedModel,
            @NotNull BlockState copiedState,
            @Nullable Direction geometryDirection,
            @NotNull BakedQuad geometryQuad,
            @NotNull RandomSource random,
            @Nullable RenderType renderType
    ) {
        Direction direction = geometryDirection;

        /*
         * If the render pass gave us a precise direction,
         * we use it.
         *
         * Otherwise, we use the real direction of the Copycat quad.
         */
        if (direction == null) {
            direction = geometryQuad.getDirection();
        }

        /*
         * For directional faces:
         * we directly ask the copied model for the quads of this face.
         */
        if (direction != null) {

            List<BakedQuad> copiedQuads =
                    copiedModel.getQuads(
                            copiedState,
                            direction,
                            random,
                            ModelData.EMPTY,
                            renderType
                    );

            if (!copiedQuads.isEmpty()) {

                int geometryTint =
                        geometryQuad.getTintIndex();

                /*
                 * Priority to a quad with the same index.
                 */
                for (BakedQuad copiedQuad : copiedQuads) {
                    if (copiedQuad.getTintIndex() == geometryTint) {
                        return copiedQuad;
                    }
                }

                /*
                 * Otherwise the first quad of this face
                 */
                return copiedQuads.get(0);
            }
        }

        /*
         * Non-directional faces.
         *
         * Example: certain internal elements or models
         * individuals.
         */
        List<BakedQuad> copiedQuads =
                copiedModel.getQuads(
                        copiedState,
                        null,
                        random,
                        ModelData.EMPTY,
                        renderType
                );

        if (!copiedQuads.isEmpty()) {
            return copiedQuads.get(0);
        }

        return null;
    }


    /*
     * ================================================================
     * UV REMAPPING
     * ================================================================
     */

    /**
     * Remaps the UV coordinates of a Copycat quad from its original
     * sprite to the sprite of the copied block.
     *
     * <p>The geometry remains unchanged. Only its texture mapping
     * is replaced.</p>
     */
    private static BakedQuad remapQuad(
            @NotNull BakedQuad sourceQuad,
            @NotNull TextureAtlasSprite sourceSprite,
            @NotNull BakedQuad copiedQuad,
            @Nullable CopycatPart part
    ) {
        TextureAtlasSprite targetSprite =
                copiedQuad.getSprite();

        if (sourceSprite == targetSprite) {
            return sourceQuad;
        }

        int[] vertices =
                sourceQuad.getVertices().clone();

        float sourceMinU =
                sourceSprite.getU0();

        float sourceMaxU =
                sourceSprite.getU1();

        float sourceMinV =
                sourceSprite.getV0();

        float sourceMaxV =
                sourceSprite.getV1();

        float targetMinU =
                targetSprite.getU0();

        float targetMaxU =
                targetSprite.getU1();

        float targetMinV =
                targetSprite.getV0();

        float targetMaxV =
                targetSprite.getV1();

        float sourceUSize =
                sourceMaxU - sourceMinU;

        float sourceVSize =
                sourceMaxV - sourceMinV;

        if (sourceUSize == 0.0F || sourceVSize == 0.0F) {
            return sourceQuad;
        }

        /*
         * Standard BLOCK vertex format:
         *
         * 0-2 : position
         * 3   : color
         * 4   : U
         * 5   : V
         * 6   : lightmap
         * 7   : normal
         */
        final int vertexSize = 8;

        for (int vertex = 0; vertex < 4; vertex++) {

            int offset =
                    vertex * vertexSize;

            float u =
                    Float.intBitsToFloat(
                            vertices[offset + 4]
                    );

            float v =
                    Float.intBitsToFloat(
                            vertices[offset + 5]
                    );

            float normalizedU =
                    (u - sourceMinU)
                            / sourceUSize;

            float normalizedV =
                    (v - sourceMinV)
                            / sourceVSize;

            float newU =
                    targetMinU
                            + normalizedU
                            * (targetMaxU - targetMinU);

            float newV =
                    targetMinV
                            + normalizedV
                            * (targetMaxV - targetMinV);

            vertices[offset + 4] =
                    Float.floatToRawIntBits(newU);

            vertices[offset + 5] =
                    Float.floatToRawIntBits(newV);
        }

        int tintIndex = copiedQuad.getTintIndex();

        if (part == CopycatPart.BOTTOM) {
            tintIndex += 1000;
        } else if (part == CopycatPart.TOP) {
            tintIndex += 2000;
        }

        /*
         * IMPORTANT:
         *
         * We take the tint index from the copied quad.
         * This allows CopycatBlockColor to be invoked for blocks
         * such as Grass Block.
         */
        return new BakedQuad(
                vertices,
                tintIndex,
                sourceQuad.getDirection(),
                targetSprite,
                sourceQuad.isShade(),
                sourceQuad.hasAmbientOcclusion()
        );
    }


    /**
     * Retextures a geometry model using the corresponding copied model.
     */
    private static List<BakedQuad> retextureModel(
            @NotNull BakedModel geometryModel,
            @NotNull BlockState copycatState,
            @NotNull BlockState copiedState,
            @Nullable Direction side,
            @NotNull RandomSource random,
            @Nullable RenderType renderType,
            @NotNull ModelData modelData
    ) {
        BakedModel copiedModel =
                CopycatModelProvider.getModel(copiedState);

        /*
         * IMPORTANT :
         *
         * The geometry must be calculated with the Copycat state,
         * not with that of the copied block.
         */
        List<BakedQuad> geometryQuads =
                geometryModel.getQuads(
                        copycatState,
                        side,
                        random,
                        modelData,
                        renderType
                );

        if (geometryQuads.isEmpty()) {
            return List.of();
        }

        List<BakedQuad> result =
                new ArrayList<>(
                        geometryQuads.size()
                );

        for (BakedQuad geometryQuad : geometryQuads) {

            Direction direction =
                    side != null
                            ? side
                            : geometryQuad.getDirection();

            BakedQuad copiedQuad =
                    findMatchingCopiedQuad(
                            copiedModel,
                            copiedState,
                            direction,
                            geometryQuad,
                            random,
                            renderType
                    );

            /*
             * Unable to find a matching texture:
             * we keep the original quad.
             */
            if (copiedQuad == null) {
                result.add(geometryQuad);
                continue;
            }

            result.add(
                    remapQuad(
                            geometryQuad,
                            geometryQuad.getSprite(),
                            copiedQuad,
                            null
                    )
            );
        }

        return result;
    }


    /*
     * ================================================================
     * QUADS
     * ================================================================
     */

    /**
     * @deprecated Use the ModelData-aware overload.
     */
    @Deprecated
    @Override
    public @NotNull List<BakedQuad> getQuads(
            @Nullable BlockState state,
            @Nullable Direction side,
            @NotNull RandomSource random
    ) {
        return getQuads(
                state,
                side,
                random,
                ModelData.EMPTY,
                null
        );
    }


    @Override
    public @NotNull List<BakedQuad> getQuads(
            @Nullable BlockState state,
            @Nullable Direction side,
            @NotNull RandomSource random,
            @NotNull ModelData modelData,
            @Nullable RenderType renderType
    ) {
        /*
         * ============================================================
         * COPYCAT CUBE
         * ============================================================
         */
        if (baseModel != null) {

            BlockState copiedState =
                    getCopiedState(
                            modelData,
                            CopycatPart.MAIN
                    );

            if (copiedState == null || copiedState.isAir()) {
                return getBaseModel().getQuads(
                        state,
                        side,
                        random,
                        modelData,
                        renderType
                );
            }

            return retextureModel(
                    getBaseModel(),
                    state,
                    copiedState,
                    side,
                    random,
                    renderType,
                    modelData
            );
        }

        /*
         * ============================================================
         * COPYCAT SLAB
         * ============================================================
         */
        if (state == null) {
            return List.of();
        }

        SlabType slabType =
                state.getValue(BlockStateProperties.SLAB_TYPE);

        /*
         * ------------------------------------------------------------
         * BOTTOM
         * ------------------------------------------------------------
         */
        if (slabType == SlabType.BOTTOM) {

            BlockState copiedState =
                    getCopiedState(
                            modelData,
                            CopycatPart.BOTTOM
                    );

            if (copiedState == null || copiedState.isAir()) {
                return getBottomModel().getQuads(
                        state,
                        side,
                        random,
                        modelData,
                        renderType
                );
            }

            return retextureModel(
                    getBottomModel(),
                    state,
                    copiedState,
                    side,
                    random,
                    renderType,
                    modelData
            );
        }

        /*
         * ------------------------------------------------------------
         * TOP
         * ------------------------------------------------------------
         */
        if (slabType == SlabType.TOP) {

            BlockState copiedState =
                    getCopiedState(
                            modelData,
                            CopycatPart.TOP
                    );

            if (copiedState == null || copiedState.isAir()) {
                return getTopModel().getQuads(
                        state,
                        side,
                        random,
                        modelData,
                        renderType
                );
            }

            return retextureModel(
                    getTopModel(),
                    state,
                    copiedState,
                    side,
                    random,
                    renderType,
                    modelData
            );
        }

        /*
         * ------------------------------------------------------------
         * DOUBLE
         * ------------------------------------------------------------
         *
         * A DOUBLE slab is still composed of two logical Copycat parts.
         *
         * Bottom half -> CopycatPart.BOTTOM
         * Top half    -> CopycatPart.TOP
         */
        if (slabType == SlabType.DOUBLE) {

            BlockState bottomState =
                    getCopiedState(
                            modelData,
                            CopycatPart.BOTTOM
                    );

            BlockState topState =
                    getCopiedState(
                            modelData,
                            CopycatPart.TOP
                    );

            boolean hasBottom =
                    bottomState != null
                            && !bottomState.isAir();

            boolean hasTop =
                    topState != null
                            && !topState.isAir();

            /*
             * No copied state at all.
             *
             * Use the normal full-block geometry.
             */
            if (!hasBottom && !hasTop) {
                return getDoubleModel().getQuads(
                        state,
                        side,
                        random,
                        modelData,
                        renderType
                );
            }

            List<BakedQuad> result =
                    new ArrayList<>();

            /*
             * ============================================================
             * BOTTOM HALF
             * ============================================================
             */

            if (hasBottom) {

                result.addAll(
                        retextureModel(
                                getBottomModel(),
                                state,
                                bottomState,
                                side,
                                random,
                                renderType,
                                modelData
                        )
                );

            } else {

                /*
                 * No copied BOTTOM:
                 * render the normal Copycat bottom texture.
                 */
                result.addAll(
                        getBottomModel().getQuads(
                                state,
                                side,
                                random,
                                modelData,
                                renderType
                        )
                );
            }

            /*
             * ============================================================
             * TOP HALF
             * ============================================================
             */

            if (hasTop) {

                result.addAll(
                        retextureModel(
                                getTopModel(),
                                state,
                                topState,
                                side,
                                random,
                                renderType,
                                modelData
                        )
                );

            } else {

                /*
                 * No copied TOP:
                 * render the normal Copycat top texture.
                 */
                result.addAll(
                        getTopModel().getQuads(
                                state,
                                side,
                                random,
                                modelData,
                                renderType
                        )
                );
            }

            return result;
        }

        return List.of();
    }


    /**
     * Returns the average Y coordinate of a quad.
     */
    private static float getAverageY(
            @NotNull BakedQuad quad
    ) {
        int[] vertices =
                quad.getVertices();

        float averageY = 0.0F;

        for (int vertex = 0; vertex < 4; vertex++) {

            int offset =
                    vertex * 8;

            averageY += Float.intBitsToFloat(
                    vertices[offset + 1]
            );
        }

        return averageY / 4.0F;
    }


    /*
     * ================================================================
     * RENDER TYPES
     * ================================================================
     */

    @Override
    public @NotNull ChunkRenderTypeSet getRenderTypes(
            @Nullable BlockState state,
            @NotNull RandomSource random,
            @NotNull ModelData modelData
    ) {

        /*
         * Render type handling is intentionally kept simple for now.
         * We will fix the cutout/translucent behavior separately.
         */

        if (baseModel != null) {

            BlockState copiedState =
                    getCopiedState(
                            modelData,
                            CopycatPart.MAIN
                    );

            if (copiedState == null
                    || copiedState.isAir()) {

                return getBaseModel().getRenderTypes(
                        state,
                        random,
                        modelData
                );
            }

            return CopycatModelProvider
                    .getModel(copiedState)
                    .getRenderTypes(
                            copiedState,
                            random,
                            modelData
                    );
        }

        return getDoubleModel().getRenderTypes(
                state,
                random,
                modelData
        );
    }


    /*
     * ================================================================
     * COMMON MODEL PROPERTIES
     * ================================================================
     */

    private BakedModel getReferenceModel() {

        if (baseModel != null) {
            return getBaseModel();
        }

        return getDoubleModel();
    }


    @Override
    public boolean useAmbientOcclusion() {
        return getReferenceModel()
                .useAmbientOcclusion();
    }


    @Override
    public boolean usesBlockLight() {
        return getReferenceModel()
                .usesBlockLight();
    }


    @Override
    public boolean isGui3d() {
        return getReferenceModel()
                .isGui3d();
    }


    @Override
    public boolean isCustomRenderer() {
        return false;
    }


    /*
     * ================================================================
     * PARTICLE
     * ================================================================
     */

    /**
     * @deprecated Use the ModelData-aware overload.
     */
    @Deprecated
    @Override
    public @NotNull TextureAtlasSprite getParticleIcon() {
        return getReferenceModel()
                .getParticleIcon();
    }


    @Override
    public @NotNull TextureAtlasSprite getParticleIcon(
            @NotNull ModelData modelData
    ) {

        BlockState copiedState =
                getCopiedState(
                        modelData,
                        CopycatPart.MAIN
                );

        if (copiedState == null
                || copiedState.isAir()) {

            return getReferenceModel()
                    .getParticleIcon(
                            modelData
                    );
        }

        return CopycatModelProvider
                .getModel(copiedState)
                .getParticleIcon(
                        modelData
                );
    }


    /*
     * ================================================================
     * TRANSFORMS
     * ================================================================
     */

    /**
     * @deprecated Use the modern transform API.
     */
    @SuppressWarnings("deprecation")
    @Deprecated
    @Override
    public @NotNull ItemTransforms getTransforms() {
        return getReferenceModel()
                .getTransforms();
    }


    @Override
    public @NotNull ItemOverrides getOverrides() {
        return getReferenceModel().getOverrides();
    }
}