package net.scp_genesis.common.copycatblocks.renderer.util;

import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.block.model.BakedQuad;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.core.Direction;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.block.state.BlockState;
import net.neoforged.neoforge.client.model.data.ModelData;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.List;

public final class CopycatModelHelper {

    private CopycatModelHelper() {
    }

    /**
     * Returns the quads generated by a copied BlockState
     * for the specified direction.
     *
     * <p>If the model does not provide directional quads,
     * general quads are requested instead.</p>
     */
    public static @NotNull List<BakedQuad> getCopiedQuads(
            @NotNull BakedModel copiedModel,
            @NotNull BlockState copiedState,
            @Nullable Direction direction,
            @NotNull RandomSource random,
            @Nullable RenderType renderType
    ) {
        List<BakedQuad> quads =
                copiedModel.getQuads(
                        copiedState,
                        direction,
                        random,
                        ModelData.EMPTY,
                        renderType
                );

        if (!quads.isEmpty()) {
            return quads;
        }

        return copiedModel.getQuads(
                copiedState,
                null,
                random,
                ModelData.EMPTY,
                renderType
        );
    }

    /**
     * Returns the quads of a copied model corresponding to
     * the direction of a Copycat geometry quad.
     */
    public static @NotNull List<BakedQuad> findMatchingCopiedQuads(
            @NotNull BakedModel copiedModel,
            @NotNull BlockState copiedState,
            @Nullable Direction geometryDirection,
            @NotNull BakedQuad geometryQuad,
            @NotNull RandomSource random,
            @Nullable RenderType renderType
    ) {
        Direction direction =
                geometryDirection != null
                        ? geometryDirection
                        : geometryQuad.getDirection();

        return getCopiedQuads(
                copiedModel,
                copiedState,
                direction,
                random,
                renderType
        );
    }
}